CREATE DATABASE AddressBook;
CREATE TABLE IF NOT EXISTS contact (
	id INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(128) NOT NULL,
	lastName VARCHAR(128) NOT NULL,
	phoneNumber VARCHAR(128) NOT NULL,
	email VARCHAR(128) NULL,
	address VARCHAR(128) NOT NULL,
	PRIMARY KEY(id)
);